-- RSI (Recursive Self-Improvement) columns for auto-tuning
ALTER TABLE polybot_config
ADD COLUMN IF NOT EXISTS rsi_auto_tuning_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS rsi_min_trades_before_adjust INTEGER DEFAULT 20,
ADD COLUMN IF NOT EXISTS rsi_max_adjustment_pct FLOAT DEFAULT 15.0,
ADD COLUMN IF NOT EXISTS rsi_adjustment_interval_hours INTEGER DEFAULT 24,
ADD COLUMN IF NOT EXISTS rsi_last_adjustment_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS kelly_sizing_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS kelly_fraction_cap FLOAT DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS kelly_min_confidence FLOAT DEFAULT 0.55,
ADD COLUMN IF NOT EXISTS kelly_max_position_pct FLOAT DEFAULT 5.0,
ADD COLUMN IF NOT EXISTS regime_detection_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS regime_vix_low_threshold FLOAT DEFAULT 15.0,
ADD COLUMN IF NOT EXISTS regime_vix_high_threshold FLOAT DEFAULT 25.0,
ADD COLUMN IF NOT EXISTS regime_vix_crisis_threshold FLOAT DEFAULT 35.0,
ADD COLUMN IF NOT EXISTS regime_auto_adjust BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS circuit_breaker_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS circuit_breaker_level1_pct FLOAT DEFAULT 2.0,
ADD COLUMN IF NOT EXISTS circuit_breaker_level2_pct FLOAT DEFAULT 4.0,
ADD COLUMN IF NOT EXISTS circuit_breaker_level3_pct FLOAT DEFAULT 8.0,
ADD COLUMN IF NOT EXISTS circuit_breaker_reset_hours INTEGER DEFAULT 24,
ADD COLUMN IF NOT EXISTS time_decay_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS time_decay_critical_days INTEGER DEFAULT 7,
ADD COLUMN IF NOT EXISTS time_decay_avoid_entry_hours INTEGER DEFAULT 24,
ADD COLUMN IF NOT EXISTS order_flow_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS depeg_detection_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS depeg_alert_threshold_pct FLOAT DEFAULT 0.3,
ADD COLUMN IF NOT EXISTS depeg_arbitrage_threshold_pct FLOAT DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS correlation_limits_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS correlation_max_cluster_pct FLOAT DEFAULT 25.0,
ADD COLUMN IF NOT EXISTS correlation_max_correlated_pct FLOAT DEFAULT 40.0;
