# PolyBot CI/CD Pipeline
# Builds, tests, and deploys to AWS ECS

name: Deploy PolyBot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: polybot
  ECS_CLUSTER: video-render-cluster
  ECS_SERVICE: polybot-service
  ECS_TASK_DEFINITION: polybot-task

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint
        run: |
          pip install flake8
          flake8 src/ --max-line-length=100 --ignore=E501
      
      - name: Type check
        run: |
          pip install mypy
          mypy src/ --ignore-missing-imports
      
      - name: Test
        run: |
          pip install pytest pytest-asyncio
          pytest tests/ -v --ignore=tests/integration || echo "No tests yet"

  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    outputs:
      image: ${{ steps.build.outputs.image }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build, tag, and push image
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Update image in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: aws/ecs-task-definition.json
          container-name: polybot
          image: ${{ needs.build.outputs.image }}
      
      - name: Create ECS service if not exists
        run: |
          # Check if polybot-service exists (only polybot, not other services)
          SERVICE_EXISTS=$(aws ecs describe-services \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE \
            --query 'services[?serviceName==`polybot-service` && status==`ACTIVE`].serviceName' \
            --output text || echo "")
          
          if [ -z "$SERVICE_EXISTS" ]; then
            echo "Creating polybot-service for first time..."
            
            # Get default VPC and subnets
            VPC_ID=$(aws ec2 describe-vpcs --filters "Name=isDefault,Values=true" --query 'Vpcs[0].VpcId' --output text)
            SUBNETS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[*].SubnetId' --output text | tr '\t' ',')
            
            # Get or create security group for polybot
            SG_ID=$(aws ec2 describe-security-groups \
              --filters "Name=group-name,Values=polybot-ecs-sg" "Name=vpc-id,Values=$VPC_ID" \
              --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || echo "None")
            
            if [ "$SG_ID" == "None" ] || [ -z "$SG_ID" ]; then
              echo "Creating security group for polybot..."
              SG_ID=$(aws ec2 create-security-group \
                --group-name polybot-ecs-sg \
                --description "Security group for PolyBot ECS tasks" \
                --vpc-id $VPC_ID \
                --query 'GroupId' --output text)
              
              # Allow outbound traffic only (bot doesn't need inbound)
              aws ec2 authorize-security-group-egress \
                --group-id $SG_ID \
                --protocol -1 \
                --cidr 0.0.0.0/0 2>/dev/null || true
            fi
            
            # Register task definition first
            aws ecs register-task-definition --cli-input-json file://aws/ecs-task-definition.json
            
            # Create the service
            aws ecs create-service \
              --cluster $ECS_CLUSTER \
              --service-name $ECS_SERVICE \
              --task-definition $ECS_TASK_DEFINITION \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SG_ID],assignPublicIp=ENABLED}"
            
            echo "✅ polybot-service created successfully"
          else
            echo "polybot-service already exists, will update"
          fi
      
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    
    steps:
      - name: Send Discord notification
        if: env.DISCORD_WEBHOOK != ''
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            COLOR=65280  # Green
            STATUS="✅ Deployed"
          else
            COLOR=16711680  # Red
            STATUS="❌ Failed"
          fi
          
          curl -H "Content-Type: application/json" \
            -d "{\"embeds\":[{\"title\":\"PolyBot Deployment\",\"description\":\"$STATUS\",\"color\":$COLOR}]}" \
            $DISCORD_WEBHOOK
